Automate creation of Jenkins credentials
eclipse-cbi/jiro pull request #123
Opened 2020-08-12 17:03 UTC by fredg02

Should those scripts be put in a sub-folder?

2020-08-20 12:02 UTC, mbarbero requested changes

2020-08-20 12:02 UTC, mbarbero commented on jenkins-create-credentials.sh
> +    ./jenkins-cli.sh "instances/${PROJECT_NAME}" create-credentials-domain-by-xml system::system::jenkins <<EOF
$script_folder

2020-08-20 12:02 UTC, mbarbero commented on jenkins-create-credentials.sh
> +    ./jenkins-cli.sh "instances/${PROJECT_NAME}" create-credentials-by-xml system::system::jenkins "${domain_name}" <<EOF
$script_folder

2020-08-20 12:02 UTC, mbarbero commented on jenkins-create-credentials.sh
> +    ./jenkins-cli.sh "instances/${PROJECT_NAME}" create-credentials-by-xml system::system::jenkins "${domain_name}" <<EOF
$script_folder

2020-08-20 12:02 UTC, mbarbero commented on jenkins-create-credentials.sh
> +    ./jenkins-cli.sh "instances/${PROJECT_NAME}" create-credentials-by-xml system::system::jenkins "${domain_name}" <<EOF
$script_folder

2020-08-20 12:02 UTC, mbarbero commented on jenkins-create-credentials.sh
> +    if [[ "${pass_domain}" == "projects-storage.eclipse.org" || "${pass_domain}" == "git.eclipse.org" ]]; then
I'm definitely not against adding a username entry to pass for *.eclipse.org entries

2020-08-20 16:00 UTC, fredg02 commented on jenkins-create-credentials-token.sh
> +    reply=$(./jenkins-cli.sh instances/${PROJECT_NAME} get-credentials-as-xml system::system::jenkins ${domain_name} ${id} 2>&1 || true)
Done.

2020-08-20 16:00 UTC, fredg02 commented on jenkins-create-credentials-token.sh
> +    ./jenkins-cli.sh "instances/${PROJECT_NAME}" create-credentials-domain-by-xml system::system::jenkins <<EOF
Done.

2020-08-20 16:00 UTC, fredg02 commented on jenkins-create-credentials.sh
> +    ./jenkins-cli.sh "instances/${PROJECT_NAME}" create-credentials-domain-by-xml system::system::jenkins <<EOF
Done.

2020-08-20 16:00 UTC, fredg02 commented on jenkins-create-credentials.sh
> +    ./jenkins-cli.sh "instances/${PROJECT_NAME}" create-credentials-by-xml system::system::jenkins "${domain_name}" <<EOF
Done.

2020-08-20 16:01 UTC, fredg02 commented on jenkins-create-credentials.sh
> +    if [[ "${pass_domain}" == "projects-storage.eclipse.org" || "${pass_domain}" == "git.eclipse.org" ]]; then
Fixed in pass and exception has been removed.

2020-08-20 16:01 UTC, fredg02 commented on jenkins-create-credentials-token.sh
> +    ./jenkins-cli.sh "instances/${PROJECT_NAME}" create-credentials-by-xml system::system::jenkins "${domain_name}" <<EOF
Done.

2020-09-03 14:51 UTC, mbarbero approved these changes

2020-09-03 14:53 UTC, merged