feat: add pass wrapper on create credential
eclipse-cbi/jiro pull request #217
Opened 2022-06-13 14:55 UTC by heurtematte

2022-06-13 16:41 UTC, mbarbero requested changes

2022-06-14 07:45 UTC, heurtematte commented on pass/pass_wrapper.sh
> +#!/usr/bin/env bash
I can do that. but my main concern is who depends on who! I wanted to avoid any circular dependency between ci-admin project and jiro, as I think jiro should be autonomous. 
Batch is not very good at manage dependencies! and over that I would preferred in this case  (sure not the best choice) duplicated code, than managed hard refactoring later.

Tell me!

2022-06-15 10:01 UTC, fredg02 commented on jenkins-create-credentials-token.sh
>  JENKINS_CLI="${script_folder}/jenkins-cli.sh"
script_folder should be renamed to SCRIPT_FOLDER (three occurrences)

2022-06-15 11:46 UTC, mbarbero commented on pass/pass_wrapper.sh
> +#!/usr/bin/env bash
so be it

2022-06-15 14:50 UTC, heurtematte commented on jenkins-create-credentials-token.sh
>  JENKINS_CLI="${script_folder}/jenkins-cli.sh"
change all 4 references
and script_name => SCRIPT_NAME

2022-06-15 15:07 UTC, mbarbero approved these changes

2022-06-15 15:07 UTC, merged